<script src="{{ url('e-sim/dist/js/vendors/dom.js') }}"></script>
<script src="{{ url('e-sim/dist/js/vendors/lucide.js') }}"></script>
<script src="{{ url('e-sim/dist/js/vendors/tippy.js') }}"></script>
<script src="{{ url('e-sim/dist/js/vendors/dayjs.js') }}"></script>
<script src="{{url('e-sim/dist/js/vendors/easepick.js')}}"></script>
<script src="{{url('e-sim/dist/js/vendors/popper.js')}}"></script>
<script src="{{url('e-sim/dist/js/vendors/dropdown.js')}}"></script>
<script src="{{url('e-sim/dist/js/vendors/chartjs.js')}}"></script>
<script src="{{url('e-sim/dist/js/vendors/vector-map.js')}}"></script>
<script src="{{url('e-sim/dist/js/vendors/tiny-slider.js')}}"></script>
<script src="{{url('e-sim/dist/js/vendors/modal.js')}}"></script>
<script src="{{url('e-sim/dist/js/vendors/simplebar.js')}}"></script>
<script src="{{url('e-sim/dist/js/pages/dashboard-overview-1.js')}}"></script>
<script src="{{url('e-sim/dist/js/components/base/page-loader.js')}}"></script>
<script src="{{url('e-sim/dist/js/components/base/lucide.js')}}"></script>
<script src="{{url('e-sim/dist/js/components/base/tippy.js')}}"></script>
<script src="{{url('e-sim/dist/js/components/base/easepick.js')}}"></script>
<script src="{{url('e-sim/dist/js/components/report-line-chart.js')}}"></script>
<script src="{{url('e-sim/dist/js/components/report-pie-chart.js')}}"></script>
<script src="{{url('e-sim/dist/js/components/report-donut-chart.js')}}"></script>
<script src="{{url('e-sim/dist/js/components/vector-map.js')}}"></script>
<script src="{{url('e-sim/dist/js/components/report-donut-chart-1.js')}}"></script>
<script src="{{url('e-sim/dist/js/components/simple-line-chart-1.js')}}"></script>
<script src="{{url('e-sim/dist/js/components/base/tiny-slider.js')}}"></script>
<script src="{{url('e-sim/dist/js/themes/rubick.js')}}"></script>
<script src="{{url('e-sim/dist/js/utils/helper.js')}}"></script>
<script src="{{url('e-sim/dist/js/components/theme-switcher.js')}}"></script>
